export const boundless = [
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-57.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-58.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-59.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-60.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-61.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-62.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-63.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-64.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-65.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-66.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-67.webp",
    "images/Boundless-Broadway_Concert/Boundless-Broadway_Concert-68.webp",
];

export const nuova = [
    "images/NUOVA-Flight/NUOVA Flight A-0863.webp",
    "images/NUOVA-Flight/NUOVA Flight A-1504.webp",
    "images/NUOVA-Flight/NUOVA Flight A-1539.webp",
    "images/NUOVA-Flight/NUOVA Flight A-1617.webp",
    "images/NUOVA-Flight/NUOVA Flight A-2275.webp",
    "images/NUOVA-Flight/NUOVA Flight A-2293.webp",
    "images/NUOVA-Flight/NUOVA Flight A-2327.webp",
    "images/NUOVA-Flight/NUOVA Flight A-2360.webp",
    "images/NUOVA-Flight/NUOVA Flight A-2442.webp",
    "images/NUOVA-Flight/NUOVA Flight A-2635.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3178.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3279.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3312.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3411.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3442.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3465.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3593.webp",
    "images/NUOVA-Flight/NUOVA Flight A-3608.webp",
    "images/NUOVA-Flight/NUOVA Flight A-5021.webp",
    "images/NUOVA-Flight/NUOVA Flight A-5026.webp",
    "images/NUOVA-Flight/NUOVA Flight A-5038.webp",
    "images/NUOVA-Flight/NUOVA Flight A-5149.webp",
    "images/NUOVA-Flight/NUOVA Flight A-5655.webp",
    "images/NUOVA-Flight/NUOVA Flight A-6466.webp",
    "images/NUOVA-Flight/NUOVA Flight A-6906.webp",
    "images/NUOVA-Flight/NUOVA Flight A-6938.webp",
    "images/NUOVA-Flight/NUOVA Flight A-8237.webp",
    "images/NUOVA-Flight/NUOVA Flight A-9011.webp",
    "images/NUOVA-Flight/NUOVA Flight A-9183.webp",
    "images/NUOVA-Flight/NUOVA Flight A-9218.webp",
    "images/NUOVA-Flight/NUOVA Flight A-9281.webp",
    "images/NUOVA-Flight/NUOVA Flight A-9313.webp",
];

export const headshot = [
    "images/Headshots/personal_headshot-1-2.webp",
    "images/Headshots/personal_headshot-1.webp",
    "images/Headshots/personal_headshot-2-2.webp",
    "images/Headshots/personal_headshot-2.webp",
    "images/Headshots/personal_headshot-3-2.webp",
    "images/Headshots/personal_headshot-3.webp",
    "images/Headshots/personal_headshot-4-2.jpg",
    "images/Headshots/personal_headshot-4.jpg",
    "images/Headshots/personal_headshot-5.jpg",
    "images/Headshots/personal_headshot-6.jpg",
    "images/Headshots/personal_headshot-7.jpg",
    "images/Headshots/personal_headshot-8.jpg",
    "images/Headshots/personal_headshot-9.jpg",
    "images/Headshots/personal_headshot-10.jpg",
    "images/Headshots/personal_headshot-11.jpg",
    "images/Headshots/personal_headshot-12.jpg",
    "images/Headshots/personal_headshot-19.jpg",
    "images/Headshots/personal_headshot-24.jpg",
    "images/Headshots/personal-headshot-1-3.jpg",
];

